### ISSUE TITLE
Integration into PgBulkInsert

### ISSUE THREAD

**Issue by bytefish** [bchapuis/stream-util#1]
@bchapuis Can I integrate the Partitioning Spliterator into PgBulkInsert? Or would you like to do it? I thought about making a dependency to your stream-util library, but I don't want to put the burden of maintaining it on you. 

By the way: I released the PostGIS Extensions to Maven, but didn't include you in the pom.xml authors list. It's not about taking the credit for it, it's just people should contact me and not you if they have problems.

**Comment by bchapuis** [comment]
@bytefish If you don't mind, I would love to do a pull request that also reference the article describing the BatchSpliterator. Then you can refactor the code and do whatever you want with it. Regarding the code, do you want me to put it in a specific package? Also, do you have any guidelines or preferences regarding the commit messages?

No problem regarding the PostGIS Extension and thank you for the credits in the README. I will definitely be one of the first users :smile:

**Comment by bytefish** [comment]
@bchapuis Great! Feel free to make a Pull Request and I will be happy to merge. As for the structure. Maybe you can put the code in a package "streams"? Besides that, no I don't have any preferences. 👍

**Comment by bchapuis** [comment]
Great, I will do that early next week :+1:

**Comment by bytefish** [comment]
Sounds good. Don't stress yourself though. 🤜🤛

**Comment by bytefish** [comment]
Thank you so much! 😎

**Comment by bchapuis** [comment]
With pleasure, I started using PgBulkInsert for large OpenStreetMap imports and it really works like a charm.
